### ISSUE TITLE
Randomly froze nvim.

### ISSUE THREAD

**Issue by lkhphuc** [anuvyklack/nvim-keymap-amend#1]
Sorry this bug report might not be very helpful, but here it goes.

My nvim keep randomly frozen indefinitely. At first I didn't know why, but then I notice it will most likely happen when I'm holding down l to move my cursor. I check `verbose map l`, `verbose map h` and saw it got mapped to an anonymous function. That wasn't very helpful, so after disabling a bunch plugins I found this to be the culprit.
Remove this plugin (and pretty-fold), the hanging stop.

My machine: MacOS M1, nvim 0.7 (and 0.8 nightly too).

**Comment by axieax** [comment]
Yeah I get this as well, related to https://github.com/anuvyklack/pretty-fold.nvim/issues/22

I have to do a ctrl-c then quit every time.

**Comment by lkhphuc** [comment]
Good to know I'm not the only one.

Mine happens randomly, even when not using Packer, and I can't even Ctr-C but has to close the terminal. 
I just disable this plugin and still use pretty-fold and it never hangs again, with a warning of missing this plugin from pretty fold.

**Comment by anuvyklack** [comment]
Tried to fix this issue. Notify me if it happens again.

**Comment by lkhphuc** [comment]
Hi, thanks for the fix but I just re-enabled it and after a few minutes it froze again. It still happens when I hold down `l` or `h` key.

**Comment by anuvyklack** [comment]
Tried to fix this issue again. Can anybody check?
